### ISSUE TITLE
Seg fault while querying finality activation block height

### ISSUE THREAD

**Issue by filippos47** [babylonlabs-io/finality-provider#121] opened 2024-11-09 09:06 UTC
Version: `v0.10.0`

Relevant log:
```shell
2024-11-09T06:53:38.073840Z	debug	the finality-provider has sufficient public randomness, skip committing more	{"pk": "74238a4148f44394d4fe0071c8b8afd84fc3c7f019c745bb6c42dacb46798819", "block_height": 22741, "last_committed_height": 24114}
2024-11-09T06:53:39.592097Z	info	the poller retrieved the block from the consumer chain	{"height": 22741}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ede1e2]

goroutine 373 [running]:
github.com/babylonlabs-io/babylon/client/query.(*QueryClient).FinalityParams(0x0?)
	/go/pkg/mod/github.com/babylonlabs-io/babylon@v0.15.0/client/query/finality.go:77 +0x42
github.com/babylonlabs-io/finality-provider/clientcontroller.(*BabylonController).QueryFinalityActivationBlockHeight(0xc0012c94a0?)
	/go/src/github.com/babylonlabs-io/finality-provider/clientcontroller/babylon.go:392 +0x19
github.com/babylonlabs-io/finality-provider/finality-provider/service.(*FinalityProviderInstance).finalitySigSubmissionLoop(0xc0012c94a0)
	/go/src/github.com/babylonlabs-io/finality-provider/finality-provider/service/fp_instance.go:207 +0xa27
created by github.com/babylonlabs-io/finality-provider/finality-provider/service.(*FinalityProviderInstance).Start in goroutine 254
	/go/src/github.com/babylonlabs-io/finality-provider/finality-provider/service/fp_instance.go:128 +0x72a
```

**Comment by gitferry** [comment] 2024-11-19 01:47
As the root cause is addressed in #277. The issue will be addressed after bumping the next Babylon version

**Closed** 2024-11-19 01:47 UTC
